// Code generated by helmit-generate. DO NOT EDIT.

package v1

import (
	"github.com/onosproject/helmit/pkg/kubernetes/resource"
)

type Client interface {
	ConfigMapsClient
	EndpointsClient
	NodesClient
	PodsClient
	SecretsClient
	ServicesClient
}

func NewClient(resources resource.Client, filter resource.Filter) Client {
	return &client{
		Client:           resources,
		ConfigMapsClient: NewConfigMapsClient(resources, filter),
		EndpointsClient:  NewEndpointsClient(resources, filter),
		NodesClient:      NewNodesClient(resources, filter),
		PodsClient:       NewPodsClient(resources, filter),
		SecretsClient:    NewSecretsClient(resources, filter),
		ServicesClient:   NewServicesClient(resources, filter),
	}
}

type client struct {
	resource.Client
	ConfigMapsClient
	EndpointsClient
	NodesClient
	PodsClient
	SecretsClient
	ServicesClient
}
