// Code generated by helmit-generate. DO NOT EDIT.

package v1

import (
	"context"
	"github.com/onosproject/helmit/pkg/kubernetes/resource"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	kubernetes "k8s.io/client-go/kubernetes"
	"time"
)

type ConfigMapsReader interface {
	Get(ctx context.Context, name string) (*ConfigMap, error)
	List(ctx context.Context) ([]*ConfigMap, error)
}

func NewConfigMapsReader(client resource.Client, filter resource.Filter) ConfigMapsReader {
	return &configMapsReader{
		Client: client,
		filter: filter,
	}
}

type configMapsReader struct {
	resource.Client
	filter resource.Filter
}

func (c *configMapsReader) Get(ctx context.Context, name string) (*ConfigMap, error) {
	configMap := &corev1.ConfigMap{}
	client, err := kubernetes.NewForConfig(c.Config())
	if err != nil {
		return nil, err
	}
	err = client.CoreV1().
		RESTClient().
		Get().
		NamespaceIfScoped(c.Namespace(), ConfigMapKind.Scoped).
		Resource(ConfigMapResource.Name).
		Name(name).
		VersionedParams(&metav1.ListOptions{}, metav1.ParameterCodec).
		Timeout(time.Minute).
		Do(ctx).
		Into(configMap)
	if err != nil {
		return nil, err
	} else {
		ok, err := c.filter(metav1.GroupVersionKind{
			Group:   ConfigMapKind.Group,
			Version: ConfigMapKind.Version,
			Kind:    ConfigMapKind.Kind,
		}, configMap.ObjectMeta)
		if err != nil {
			return nil, err
		} else if !ok {
			return nil, errors.NewNotFound(schema.GroupResource{
				Group:    ConfigMapKind.Group,
				Resource: ConfigMapResource.Name,
			}, name)
		}
	}
	return NewConfigMap(configMap, c.Client), nil
}

func (c *configMapsReader) List(ctx context.Context) ([]*ConfigMap, error) {
	list := &corev1.ConfigMapList{}
	client, err := kubernetes.NewForConfig(c.Config())
	if err != nil {
		return nil, err
	}
	err = client.CoreV1().
		RESTClient().
		Get().
		NamespaceIfScoped(c.Namespace(), ConfigMapKind.Scoped).
		Resource(ConfigMapResource.Name).
		VersionedParams(&metav1.ListOptions{}, metav1.ParameterCodec).
		Timeout(time.Minute).
		Do(ctx).
		Into(list)
	if err != nil {
		return nil, err
	}

	results := make([]*ConfigMap, 0, len(list.Items))
	for _, configMap := range list.Items {
		ok, err := c.filter(metav1.GroupVersionKind{
			Group:   ConfigMapKind.Group,
			Version: ConfigMapKind.Version,
			Kind:    ConfigMapKind.Kind,
		}, configMap.ObjectMeta)
		if err != nil {
			return nil, err
		} else if ok {
			copy := configMap
			results = append(results, NewConfigMap(&copy, c.Client))
		}
	}
	return results, nil
}
