// Code generated by helmet-generate. DO NOT EDIT.

package v1

import (
	"github.com/onosproject/helmet/pkg/helm/api/resource"
)

type ConfigMapsClient interface {
	ConfigMaps() ConfigMapsReader
}

func NewConfigMapsClient(resources resource.Client, filter resource.Filter) ConfigMapsClient {
	return &configMapsClient{
		Client: resources,
		filter: filter,
	}
}

type configMapsClient struct {
	resource.Client
	filter resource.Filter
}

func (c *configMapsClient) ConfigMaps() ConfigMapsReader {
	return NewConfigMapsReader(c.Client, c.filter)
}
